######################################################################
## NOTE: THIS FILE SHOULD BE REPLACED BY RUNNING ./script/bootstrap ##
######################################################################

[tool.poetry]
name = "python-template"
version = "1.0.0"
description = ""
authors = ["Armand Sauzay <sauzayarmand@gmail.com>"]
readme = "README.md"
packages = [{include = "python_template"}]

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.test.dependencies]
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
